<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <CodeAnalysisRuleSet>..\cake.json.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="$(SolutionDir)/stylecop.json" Link="stylecop.json" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>Cake.Json</PackageId>
    <Title>Cake.Json</Title>
    <Summary>JSON Serialization and manipulation addon for cake build.</Summary>
    <Description>Cake Build addon for JSON Serialization and manipulation.</Description>
    <PackageTags>cake;cake-build;cake-addin;addin;script;build;json;newtonsoft;serialization</PackageTags>
    <Authors>Redth</Authors>
    <Owners>Redth, cake-contrib</Owners>
    <RepositoryUrl>https://github.com/cake-contrib/Cake.Json.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/cake-contrib/Cake.Json</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cake.Core" Version="6.0.0" PrivateAssets="All" />
    <PackageReference Include="Cake.Common" Version="6.0.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Cake.Addin.Analyzer" Version="0.1.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="CakeContrib.Guidelines" Version="1.7.0" PrivateAssets="All" />
    <PackageReference Include="IDisposableAnalyzers" Version="4.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="stylecop.analyzers" Version="1.1.118">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
