name: Draft Release Notes

on:
  workflow_dispatch:

jobs:
  draft-stable:
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout the requested branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - name: Cache Tools
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}
      - name: Set up git version
        if: ${{ !contains(github.ref, '/hotfix/') && !contains(github.ref, '/release/') }}
        uses: gittools/actions/gitversion/setup@31b3198b2de324472547fecec2c0f721b70c38e2 # v0.9.15
        with:
          versionSpec: "5.x"
      - name: Run git version
        if: ${{ !contains(github.ref, '/hotfix/') && !contains(github.ref, '/release/') }}
        id: gitversion
        uses: gittools/actions/gitversion/execute@31b3198b2de324472547fecec2c0f721b70c38e2 # v0.9.15
      - name: Create release branch ${{ github.event.inputs.version }}
        if: ${{ steps.gitversion.outputs.majorMinorPatch }}
        run: git switch -c release/${{ steps.gitversion.outputs.majorMinorPatch }}
      - name: Push new branch
        if: ${{ steps.gitversion.outputs.majorMinorPatch }}
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df # v0.8.0
        with:
          branch: "release/${{ steps.gitversion.outputs.majorMinorPatch }}"
          github_token: ${{ secrets.GH_TOKEN }}
      - name: Drafting Release Notes
        uses: cake-build/cake-action@a6eb054329257c9e70a6c6bf01747ad6e1d9d52b # v1
        with:
          script-path: recipe.cake
          target: releasenotes
          verbosity: Diagnostic
          cake-version: 0.38.5
          cake-bootstrap: true
